### ISSUE TITLE
Building image from source results in: Error: Failed to synchronize cache for repo 'updates' on Fedora 24

### ISSUE THREAD

**Issue by jaegerbane** [cybermaggedon/accumulo-docker#1]
Not sure this repo is still being maintained but -

I've been looking at modifying some of these sources to stand up a container-ised Accumulo with an up-to-date version of Gaffer installed (0.6.6 as of writing). 

As part of that I've been modifying the sources and re-building as a newly-tagged image, and I'm finding that a simple `docker build -t <cybermaggedon/accumulo-gaffer:0.6.6g>` results in the following error:

`Error: Failed to synchronize cache for repo 'updates'
The command '/bin/sh -c dnf install -y tar' returned a non-zero code: 1`

From what I can tell, it seems that this kind of error normally appears if there's some kind of issue with the internet connection of the box. I *think* it's down to a proxy issue but setting the proxy explicitly on the command line doesn't change anything, i.e.

`docker build --build-arg http_proxy="<proxy address as stated in docker info>" -t <cybermaggedon/accumulo-gaffer:0.6.6g>`

...produces the same result. 

Running the same dnf command on the command line works fine.

**Comment by jaegerbane** [comment]
In case anyone needs it, I figured out how to fix this:

The error is indeed tied to a connectivity issue - in this case, the proxy details weren't being updated. The main gotcha was that setting them as `--build-args` on the command line doesn't work and doesn't display any errors to show it hasn't.

I had to set them as ENVs in the Dockerfile. Worked fine after that.

**Comment by cybermaggedon** [comment]
Yeh, still maintained, but have been a bit busy.  I'm running Gaffer on Accumulo in Kubernetes on Google cloud. Soon be time for a Gaffer upgrade.

**Comment by jaegerbane** [comment]
Awesome - are you using Kubernetes from scratch or are you using GKEs?

**Comment by cybermaggedon** [comment]
@csmallon, yes using GKE.
